// flow-typed signature: 041323b9c6d6c63beec74fb8af3a228b
// flow-typed version: <<STUB>>/react-linechart_v^1.1.12/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-linechart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-linechart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-linechart/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-linechart/example/App' {
  declare module.exports: any;
}

declare module 'react-linechart/example/constants/gsm' {
  declare module.exports: any;
}

declare module 'react-linechart/example/constants/points' {
  declare module.exports: any;
}

declare module 'react-linechart/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-linechart/dist/bundle.js' {
  declare module.exports: $Exports<'react-linechart/dist/bundle'>;
}
declare module 'react-linechart/example/App.js' {
  declare module.exports: $Exports<'react-linechart/example/App'>;
}
declare module 'react-linechart/example/constants/gsm.js' {
  declare module.exports: $Exports<'react-linechart/example/constants/gsm'>;
}
declare module 'react-linechart/example/constants/points.js' {
  declare module.exports: $Exports<'react-linechart/example/constants/points'>;
}
declare module 'react-linechart/example/index.js' {
  declare module.exports: $Exports<'react-linechart/example/index'>;
}
